Add "/MP" compiler flag for MSVC to speed up build process.
fougue/mayo pull request #311
Opened 2024-12-06 12:09 UTC by CreativeLau

2024-12-10 09:23 UTC, HuguesDelorme requested changes
For me the changes should just check if cmake generator is VisualStudio. If yes then straight add /MP to `Mayo_CompileOptions` cmake variable

2024-12-11 02:18 UTC, CreativeLau commented
Definitely, it should be modified as your recommendation. I have changed the pull request.

2024-12-11 14:28 UTC, HuguesDelorme requested changes
Addition of `/MP` should happen only when cmake generator is VisualStudio(ie cmake creates VisualStudio projects)
Otherwise this option will break build of other make systems(eg ninja, nmake, ...)

2024-12-16 10:24 UTC, CreativeLau commented
Yes, the /MP will be appended only if the compiler is MSVC.

2026-03-13 16:29 UTC, HuguesDelorme commented
Covered by https://github.com/fougue/mayo/commit/3e5205e632a609321e30ad2badb2e1e963a234d0
Thanks for the suggestion!

2026-03-13 16:29 UTC, closed without merging